### ISSUE TITLE
please update atomic_pointer.h so it support aarch64

### ISSUE THREAD

**Issue by mst100** [zettel-kasten/zettelkasten#9]
Hey dev, can you update ~/zettelkasten/src/leveldb/port/atomic_pointer.h to support aarch64
so that Armv8 SBC can mine it

**Comment by zettel-kasten** [comment]
ok, I have added the solution:

https://github.com/zettel-kasten/zettelkasten/commit/69af7f750f9469c2bc1cd7dd9417327a875ec3f1

please test, so I can close this issue. 

Thanks

**Comment by zettel-kasten** [comment]
tested and works. Closing.
